#!/bin/bash
#PBS -S /bin/sh

#PBS -A wellman_flux
#PBS -q flux
#PBS -N mas-epp_sim
#PBS -t 2368,2369,2370
#PBS -o /home/wellmangroup/many-agent-simulations/epp_sim-testing/epp_sim/../simulations/${PBS_ARRAYID}/out
#PBS -e /home/wellmangroup/many-agent-simulations/epp_sim-testing/epp_sim/../simulations/${PBS_ARRAYID}/out
mkdir /tmp/${PBS_JOBID}; cd /tmp/${PBS_JOBID}; cp -r /home/wellmangroup/many-agent-simulations/epp_sim-testing/epp_sim/* .; cp -r /home/wellmangroup/many-agent-simulations/epp_sim-testing/epp_sim/../simulations/${PBS_ARRAYID} .
/tmp/${PBS_JOBID}/script/batch /tmp/${PBS_JOBID}/${PBS_ARRAYID} 30
cp -r ${PBS_ARRAYID} /home/wellmangroup/many-agent-simulations/epp_sim-testing/epp_sim/../simulations; /bin/rm -rf /tmp/${PBS_JOBID}; chown -R bcassell /home/wellmangroup/many-agent-simulations/epp_sim-testing/epp_sim/../simulations/${PBS_ARRAYID}