# IMPORTANT: This file is generated by cucumber-rails - edit at your own peril.
# It is recommended to regenerate this file in the future when you upgrade to a
# newer version of cucumber-rails. Consider adding your own code to a new file
# instead of editing this one. Cucumber will automatically load all features/**/*.rb
# files.
require 'rubygems'
require 'spork'

Spork.prefork do
  require 'fabrication'
  require 'cucumber/rails'
  require 'resque_spec/scheduler'
  Capybara.default_selector = :css
  Capybara.javascript_driver = :webkit
  Capybara.default_wait_time = 5
  require 'cucumber/rspec/doubles'
  ActionController::Base.allow_rescue = false
  World(ResqueSpec::Helpers)
end

Spork.each_run do
  ResqueSpec.reset!
end