defaults: &defaults
  host: localhost
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

development:
  <<: *defaults
  database: egt_web_interface_development

test:
  <<: *defaults
  database: egt_web_interface_test

# set these environment variables on your prod server
production:
  host: localhost
  port: 27017
  database: egt_web_interface_production
