check_simulations:
  cron: "*/5 * * * *"
  class: SimulationChecker
  queue: nyx_actions
  args:
  description: "This job checks nyx for status updates on simulations, and gathers completed simulations."

clean_simulations:
  cron: "0 0 * * *"
  class: SimulationCleaner
  queue: nyx_actions
  args:
  description: "This job removes stale simulations from the database."