development:
    host: "nyx-login.engin.umich.edu"
    deploy_path: "/home/wellmangroup/many-agent-simulations"

test:
    host: "d-108-200"
    deploy_path: "/Users/bcassell/testing"
    
production:
    host: "nyx-login.engin.umich.edu"
    deploy_path: "/home/wellmangroup/many-agent-simulations"