development:
    host: "nyx-login-amd.engin.umich.edu"
    deploy_path: "/home/wellmangroup/many-agent-simulations"

test:
    host: "d-108-249.eecs.umich.edu"
    deploy_path: "/home/bcassell/Test"

production:
    host: "nyx-login-amd.engin.umich.edu"
    deploy_path: "/home/wellmangroup/many-agent-simulations"