defaults: &defaults
    deploy_path: "/home/wellmangroup/many-agent-simulations"
    simulations_path: "/home/bcassell/simulations"
    error_store: 512

development:
    <<: *defaults

staging:
    <<: *defaults

test:
    <<: *defaults
    deploy_path: "/Users/bcassell/testing"
    simulations_path: "/home/bcassell/testing"
    error_store: 128

production:
    <<: *defaults
    error_store: 1024