#!/bin/bash
#PBS -S /bin/sh

#PBS -q route
#PBS -N mas-equity_premium_simulator
#PBS -t 9558,9560
#PBS -o /home/wellmangroup/many-agent-simulations/epp_sim/../simulations/${PBS_ARRAYID}/out
#PBS -e /home/wellmangroup/many-agent-simulations/epp_sim/../simulations/${PBS_ARRAYID}/out
mkdir /tmp/${PBS_JOBID}; cd /tmp/${PBS_JOBID}; cp -r /home/wellmangroup/many-agent-simulations/epp_sim/* .; cp -r /home/wellmangroup/many-agent-simulations/epp_sim/../simulations/${PBS_ARRAYID} .
/tmp/${PBS_JOBID}/script/batch /tmp/${PBS_JOBID}/${PBS_ARRAYID} 30
cp -r ${PBS_ARRAYID} /home/wellmangroup/many-agent-simulations/epp_sim/../simulations; /bin/rm -rf /tmp/${PBS_JOBID}; chgrp -R wellman /home/wellmangroup/many-agent-simulations/epp_sim/../simulations/${PBS_ARRAYID}; chmod -R ug+wrx /home/wellmangroup/many-agent-simulations/epp_sim/../simulations/${PBS_ARRAYID}