require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe SchedulersController do

  def mock_scheduler(stubs={})
    @mock_scheduler ||= mock_model(Scheduler, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all schedulers as @schedulers" do
      Scheduler.stub(:all) { [mock_scheduler] }
      get :index
      assigns(:schedulers).should eq([mock_scheduler])
    end
  end

  describe "GET show" do
    it "assigns the requested scheduler as @scheduler" do
      Scheduler.stub(:find).with("37") { mock_scheduler }
      get :show, :id => "37"
      assigns(:scheduler).should be(mock_scheduler)
    end
  end

  describe "GET new" do
    it "assigns a new scheduler as @scheduler" do
      Scheduler.stub(:new) { mock_scheduler }
      get :new
      assigns(:scheduler).should be(mock_scheduler)
    end
  end

  describe "GET edit" do
    it "assigns the requested scheduler as @scheduler" do
      Scheduler.stub(:find).with("37") { mock_scheduler }
      get :edit, :id => "37"
      assigns(:scheduler).should be(mock_scheduler)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created scheduler as @scheduler" do
        Scheduler.stub(:new).with({'these' => 'params'}) { mock_scheduler(:save => true) }
        post :create, :scheduler => {'these' => 'params'}
        assigns(:scheduler).should be(mock_scheduler)
      end

      it "redirects to the created scheduler" do
        Scheduler.stub(:new) { mock_scheduler(:save => true) }
        post :create, :scheduler => {}
        response.should redirect_to(scheduler_url(mock_scheduler))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved scheduler as @scheduler" do
        Scheduler.stub(:new).with({'these' => 'params'}) { mock_scheduler(:save => false) }
        post :create, :scheduler => {'these' => 'params'}
        assigns(:scheduler).should be(mock_scheduler)
      end

      it "re-renders the 'new' template" do
        Scheduler.stub(:new) { mock_scheduler(:save => false) }
        post :create, :scheduler => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested scheduler" do
        Scheduler.stub(:find).with("37") { mock_scheduler }
        mock_scheduler.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :scheduler => {'these' => 'params'}
      end

      it "assigns the requested scheduler as @scheduler" do
        Scheduler.stub(:find) { mock_scheduler(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:scheduler).should be(mock_scheduler)
      end

      it "redirects to the scheduler" do
        Scheduler.stub(:find) { mock_scheduler(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(scheduler_url(mock_scheduler))
      end
    end

    describe "with invalid params" do
      it "assigns the scheduler as @scheduler" do
        Scheduler.stub(:find) { mock_scheduler(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:scheduler).should be(mock_scheduler)
      end

      it "re-renders the 'edit' template" do
        Scheduler.stub(:find) { mock_scheduler(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested scheduler" do
      Scheduler.stub(:find).with("37") { mock_scheduler }
      mock_scheduler.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the schedulers list" do
      Scheduler.stub(:find) { mock_scheduler }
      delete :destroy, :id => "1"
      response.should redirect_to(schedulers_url)
    end
  end

end
